apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: rca-testbed-social
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root1234
  MYSQL_DATABASE: socialfeed
  MYSQL_USER: socialfeed
  MYSQL_PASSWORD: socialfeed1234
