server:
  port: 8083

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/commerce
    username: ${DB_USER:commerce}
    password: ${DB_PASS:commerce1234}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: payment_schema
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  health:
    kafka:
      enabled: false

outbox:
  relay:
    enabled: true

topics:
  payments: commerce.payments

pg:
  api:
    base-url: ${PG_API_URL:http://192.168.200.109:8090}
    connect-timeout: 3s
    read-timeout: 10s

services:
  banking-transfer:
    base-url: ${BANKING_TRANSFER_URL:http://testbed-transfer.rca-testbed-banking.svc.cluster.local:8082}
    connect-timeout: 3s
    read-timeout: 10s
