apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: rca-testbed-food
type: Opaque
stringData:
  POSTGRES_DB: fooddelivery
  POSTGRES_USER: fooddelivery
  POSTGRES_PASSWORD: fooddelivery1234
