apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: rca-testbed-food
data:
  DB_HOST: testbed-mysql
  DB_PORT: "3306"
  DB_NAME: fooddelivery

  KAFKA_BOOTSTRAP_SERVERS: testbed-kafka:9092

  ORDER_SERVICE_URL: http://testbed-order:8080
  RESTAURANT_SERVICE_URL: http://testbed-restaurant:8081
  DISPATCH_SERVICE_URL: http://testbed-dispatch:8082
  PAYMENT_SERVICE_URL: http://testbed-payment:8083

  PG_API_URL: http://testbed-external-pg-mock:9090
