apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbed-payment
  namespace: rca-testbed-food
  labels:
    app: testbed-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbed-payment
  template:
    metadata:
      labels:
        app: testbed-payment
    spec:
      volumes:
        - name: apm-agent
          hostPath:
            path: /opt/polestar10/apm
            type: Directory
      containers:
        - name: payment-service
          image: food-delivery-payment:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: service-config
          volumeMounts:
            - name: apm-agent
              mountPath: /opt/apm
              readOnly: true
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/opt/apm/opentelemetry-javaagent.jar"
            - name: OTEL_SERVICE_NAME
              value: "food-delivery-payment"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://192.168.230.119:14317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "lucida.groupId=food-delivery,lucida.target_id=2e6120e3-37fa-4c44-a224-6ab13afdd9ee"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "10000"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 5
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: testbed-payment
  namespace: rca-testbed-food
spec:
  selector:
    app: testbed-payment
  ports:
    - port: 8083
      targetPort: 8083
