apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: rca-testbed-commerce
type: Opaque
stringData:
  POSTGRES_DB: commerce
  POSTGRES_USER: commerce
  POSTGRES_PASSWORD: commerce1234
