-- core-banking schema (Oracle 23ai Free — gvenzl/oracle-free)
-- 실행 컨텍스트 주의: /container-entrypoint-initdb.d 의 스크립트는 APP_USER 가 아니라
-- **SYSDBA 로 실행**된다 (2026-07-13 109 실배포에서 확인 — 테이블이 전부 SYS 소유로
-- 생성되고 트리거는 ORA-04089 로 실패, 앱(banking 접속)은 ORA-00942).
-- 그래서 아래 두 줄로 대상 PDB·스키마를 명시한다. banking 유저 자체는 이미지가
-- ORACLE_PASSWORD+APP_USER+APP_USER_PASSWORD 로 부트스트랩한다.
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = BANKING;
--
-- 4개 테이블: accounts, transfers, ledger_entries, outbox_events.
-- 이체(transfer)는 accounts 를 FOR UPDATE 로 lock → row-lock 경합 표면.
-- ledger_entries 는 이체 이벤트를 복식부기로 반영(worker, Kafka banking.transfers 구독).
-- outbox_events 는 outbox 패턴(DB 트랜잭션-이벤트 발행 원자화) 저장소.

CREATE TABLE accounts (
    id          VARCHAR2(64) PRIMARY KEY,
    holder      VARCHAR2(128) NOT NULL,
    balance     NUMBER(18,2) DEFAULT 0 NOT NULL,
    status      VARCHAR2(16) DEFAULT 'ACTIVE' NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_accounts_updated_at
    BEFORE UPDATE ON accounts
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE transfers (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_ref  VARCHAR2(64) NOT NULL UNIQUE,
    from_account  VARCHAR2(64) NOT NULL,
    to_account    VARCHAR2(64) NOT NULL,
    amount        NUMBER(18,2) NOT NULL,
    status        VARCHAR2(16) DEFAULT 'PENDING' NOT NULL,
    order_id      VARCHAR2(64),
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX idx_transfers_from ON transfers (from_account);
CREATE INDEX idx_transfers_to ON transfers (to_account);
CREATE INDEX idx_transfers_order ON transfers (order_id);
CREATE INDEX idx_transfers_status ON transfers (status);
CREATE INDEX idx_transfers_created ON transfers (created_at);

CREATE TABLE ledger_entries (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_ref  VARCHAR2(64) NOT NULL,
    account_id    VARCHAR2(64) NOT NULL,
    direction     VARCHAR2(8) NOT NULL,
    amount        NUMBER(18,2) NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX idx_ledger_ref ON ledger_entries (transfer_ref);
CREATE INDEX idx_ledger_account ON ledger_entries (account_id);

-- outbox 패턴(commerce 정본 템플릿과 동일 컬럼 구성). transfer-service/ledger-service 가 공용으로 사용.
CREATE TABLE outbox_events (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type  VARCHAR2(50) NOT NULL,
    aggregate_id    VARCHAR2(50) NOT NULL,
    event_type      VARCHAR2(50) NOT NULL,
    topic           VARCHAR2(100) NOT NULL,
    payload         CLOB NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP,
    published_at    TIMESTAMP
);
CREATE INDEX idx_outbox_unpublished ON outbox_events (published_at, created_at);

-- ============================================================
-- 시드 데이터: 계좌 14개(개인/법인 혼합, 잔액 보유)
-- 'commerce-settlement'/'commerce-merchant' 는 commerce/payment-service의
-- BankingTransferClient 가 이체 fromAccount/toAccount 로 호출하는
-- 고정 계좌 ID — cross-domain 시드 정합을 위해 실제 계좌로 시딩한다.
-- MERGE 로 idempotent 재실행 보장(MySQL ON DUPLICATE KEY UPDATE 대응).
-- ============================================================
MERGE INTO accounts a
USING (
    SELECT 'ACC-1001' AS id, '김민수' AS holder, 5000000.00 AS balance, 'ACTIVE' AS status FROM dual UNION ALL
    SELECT 'ACC-1002', '이서연', 3200000.00, 'ACTIVE' FROM dual UNION ALL
    SELECT 'ACC-1003', '박지훈', 1500000.00, 'ACTIVE' FROM dual UNION ALL
    SELECT 'ACC-1004', '최유진', 800000.00, 'ACTIVE' FROM dual UNION ALL
    SELECT 'ACC-1005', '정우성', 12000000.00, 'ACTIVE' FROM dual UNION ALL
    SELECT 'ACC-1006', '한소희', 450000.00, 'ACTIVE' FROM dual UNION ALL
    SELECT 'ACC-1007', '오세훈', 2750000.00, 'ACTIVE' FROM dual UNION ALL
    SELECT 'ACC-2001', '플롭베이프(주)', 88000000.00, 'ACTIVE' FROM dual UNION ALL
    SELECT 'ACC-2002', '누리 커머스', 45000000.00, 'ACTIVE' FROM dual UNION ALL
    SELECT 'ACC-2003', '배달의고수', 23000000.00, 'ACTIVE' FROM dual UNION ALL
    SELECT 'ACC-9001', '동결계좌 A', 100000.00, 'FROZEN' FROM dual UNION ALL
    SELECT 'ACC-9002', '해지계좌 B', 0.00, 'CLOSED' FROM dual UNION ALL
    -- 정산 계좌는 두 상시 소비자(checkout당 이체 + 매시 정산 배치)가 출금만 하는 저수지다.
    -- 5천만이면 반나절에 고갈돼 이체가 전부 FAILED로 침묵 실패한다(2026-07-20 실증, 5일간 27.5만 건).
    SELECT 'commerce-settlement', '커머스 정산 계좌', 1000000000000.00, 'ACTIVE' FROM dual UNION ALL
    SELECT 'commerce-merchant', '커머스 가맹점 계좌', 10000000.00, 'ACTIVE' FROM dual
) src
ON (a.id = src.id)
WHEN MATCHED THEN UPDATE SET a.holder = src.holder
WHEN NOT MATCHED THEN INSERT (id, holder, balance, status) VALUES (src.id, src.holder, src.balance, src.status);

COMMIT;
