apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: rca-testbed-banking
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: root1234
  MARIADB_DATABASE: banking
  MARIADB_USER: banking
  MARIADB_PASSWORD: banking1234
